GET http://localhost:8000/member/member/count
Accept: application/json

###
# 快捷输入ptrp
POST http://localhost:8000/member/member/register
Content-Type: application/x-www-form-urlencoded

mobile=1234

###
POST http://localhost:8000/member/member/send-code
Content-Type: application/json

{
  "mobile": "12345677654"
}

###
POST http://localhost:8000/member/member/login
Content-Type: application/json

{
  "mobile": "12345673355",
  "code": "8888"
}


###
